name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  package-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-and-install-pnpm
      - name: Package JSON - monorepo
        run: pnpm sort-package-json:check
      - name: Package JSON
        run: turbo run sort-package-json:check

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-and-install-pnpm
      - name: Prettier - monorepo
        run: pnpm prettier:check
      - name: Prettier
        run: turbo run prettier:check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-and-install-pnpm
      - name: Lint
        run: turbo run lint

  unused-exports:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-and-install-pnpm
      - name: Unused Exports
        run: turbo run unused-exports
